# Markdown
markdown : kramdown

kramdown :
  hard_wrap : false
  syntax_highlighter : rouge

# Outputting
permalink : /blog/:title
timezone: Europe/Berlin
# paginate: 20

# Site Variables
title : Thoughts on front end development
description : Web design including UI, UX, HTML, CSS, JavaScript and Node
url : https://vincentp.me
version : v7

# Personal Variables
author:
  pinboard :
    url: https://www.pinboard.in/u:monkeymajiks/public
    username: monkeymajiks
  github :
    url : https://www.github.com/vipickering
    username: vipickering
  twitter :
    url : https://twitter.com/vipickering
    username : vipickering
  feed : http://feeds.feedburner.com/vincentp
  email : hello@vincentp.me
  job : UI/UX Consultant
  name : Vincent Pickering

# Gems
