# Markdown
markdown : kramdown
highlighter: rouge
#Syntax Highlighting
# kramdown :
#   input: GFM
#   hard_wrap : false
#   syntax_highlighter : rouge

#Collections
# collections:
#   posts:
#     output: true
#     permalink: /blog/amp/:title/
#     values:
#       layout: amp


# Outputting
permalink : /blog/:title
timezone: Europe/London
# paginate: 20

# Site Variables
title : Thoughts on frontend development
description : Web design including UI, UX, HTML, CSS, JavaScript and Node
url : https://vincentp.me
version : 10
available: true

# Exclude Files
exclude:
  - "postcss.config.js"
  - "Gemfile"
  - "Gemfile.lock"
  - "package.json"
  - "node_modules"
  - "LICENSE"

include:
  - "_headers"
  - "_redirects"
