# Markdown
markdown : kramdown

kramdown :
  hard_wrap : false
  # syntax_highlighter : rouge

# Outputting
permalink : /blog/:title
timezone: Europe/Berlin
# paginate: 20

# Site Variables
title : Thoughts on front end development
description : Web design including UI, UX, HTML, CSS, JavaScript and Node
url : https://vincentp.me
version : v7.0

# Exclude Files
exclude:
  - "postcss.config.js"
