# Markdown
markdown : kramdown

#Syntax Highlighting
kramdown :
  hard_wrap : false
  # syntax_highlighter : rouge

#Collections
# collections:
#   posts:
#     output: true
#     permalink: /blog/amp/:title/
#     values:
#       layout: amp


# Outputting
permalink : /blog/:title
timezone: Europe/London
# paginate: 20

# Site Variables
title : Thoughts on front end development
description : Web design including UI, UX, HTML, CSS, JavaScript and Node
url : https://vincentp.me
version : v7.1

# Exclude Files
exclude:
  - "postcss.config.js"
  - "Gemfile"
  - "Gemfile.lock"
  - "package.json"
  - "node_modules"
  - "LICENSE"
