[[redirects]]
    from = "/categories/tips/"
    to = "/"
    status = 301

[[headers]]
    for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000"
    Link = '''
    </css/application.min.css>; rel=preload; as=style'''
