# Markdown
markdown: kramdown

kramdown:
  # input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Outputting
permalink: /blog/:title
paginate: 20

# Site Variables
name: Vincent Pickering UI/UX Consultant
url: http://vincentp.me
version: v6.0

author:
  twitter: http://www.twitter.com/vipickering
  github: http://www.github.com/vipickering
  googleplus: https://plus.google.com/u/0/+VincentPickering/?rel=author
  feed: http://feeds.feedburner.com/vincentp
  email: hello@vincentp.me
  job: UI/UX Consultant
  name: Vincent Pickering

# Gems
gems: [jekyll-paginate, jekyll-contentblocks, jekyll-gist]
